name: live_activities
description: A Flutter plugin to use iOS 16.1+ Live Activities & iPhone 14 Pro Dynamic Island features
version: 1.9.5
homepage: https://dimitridessus.fr/
repository: https://github.com/istornz/live_activities

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=2.5.0"

screenshots:
  - description: 'Display a live activity on the iPhone 14 Pro+ dynamic island.'
    path: images/showcase/static/dynamic_island.webp
  - description: 'Display a live activity on the lockscreen.'
    path: images/showcase/static/lockscreen_live_activity.webp
  - description: 'Create a new live activity with the live_activities plugin.'
    path: images/showcase/animations/create_live_activity.webp
  - description: 'Update a live activity with the live_activities plugin.'
    path: images/showcase/animations/update_live_activity.webp
  - description: 'live_activities plugin logo.'
    path: images/logo.webp

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  path_provider_foundation: ^2.4.0
  path_provider: ^2.1.4
  flutter_native_image: ^0.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LiveActivitiesPlugin
      android:
        package: com.flutter_live_activities
        pluginClass: FlutterLiveActivitiesPlugin